jobs:
  add-collaborator:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionar colaborador com GH CLI
        env:
          GH_TOKEN: ${{ secrets.TESTE_API }}
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/NayaraLetycia/gerenciador_albuns/collaborators/tentaculo-ops \
            -f permission='push'
