name: Add collaborator

on:
  push:

jobs:
  add-collaborator:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionar colaborador via API
        env:
          GH_TOKEN: ${{ secrets.TESTE_API }}
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/NayaraLetycia/gerenciador_albuns/collaborators/tentaculo-ops \
            -d '{"permission":"pull"}'
