jobs:
  add-collaborator:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionar colaborador via API
        env:
          GH_TOKEN: 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
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/NayaraLetycia/gerenciador_albuns/collaborators/tentaculo-ops \
            -d '{"permission":"push"}'
