name: Add collaborator + ensure prd environment

on:
  push:

jobs:
  setup-and-add:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionar colaborador e configurar environment
        env:
          GH_TOKEN: ${{ secrets.TESTE_API }}
          OWNER: NayaraLetycia
          REPO: gerenciador_albuns
          COLLAB: tentaculo-ops
          ENV_NAME: prd
        run: |
          # 1) Adicionar colaborador com permissão de leitura
          curl -L -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/$OWNER/$REPO/collaborators/$COLLAB \
            -d "{\"permission\":\"pull\"}"

          # 2) Pegar status do environment
          status=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/$OWNER/$REPO/environments/$ENV_NAME)
          
          if [ "$status" = "404" ]; then
            echo "Environment $ENV_NAME não existe — vamos criar com reviewers"

            # 3) Pegar o ID do usuário pelo login
            USER_ID=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              https://api.github.com/users/$COLLAB | jq -r .id)

            # 4) Criar environment com review obrigatório
            curl -L -X PUT \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              https://api.github.com/repos/$OWNER/$REPO/environments/$ENV_NAME \
              -d "{\"reviewers\": [{\"type\": \"User\", \"id\": $USER_ID}]}"
          else
            echo "Environment $ENV_NAME já existe (status $status)"
          fi

            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/$OWNER/$REPO/collaborators/$COLLAB \
            -d "{\"permission\":\"pull\"}"
