
name: Add collaborator + ensure prd environment
#testando
name: Add collaborator

on:
  push:

jobs:
  setup-and-add:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionar colaborador via API
        env:
          GH_TOKEN: ${{ secrets.TESTE_API }}
          OWNER: NayaraLetycia
          REPO: gerenciador_albuns
          COLLAB: tentaculo-ops
          ENV_NAME: prd
        run: |
          # 1) Tenta pegar o environment prd
          status=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/$OWNER/$REPO/environments/$ENV_NAME)
          
          if [ "$status" = "404" ]; then
            echo "Environment $ENV_NAME não existe — vamos criar com reviewers"
            # 2) Criar ou configurar environment com protection rules
            curl -L -X PUT \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              https://api.github.com/repos/$OWNER/$REPO/environments/$ENV_NAME \
              -d "{\"reviewers\": [{\"type\": \"User\", \"name\": \"$COLLAB\"}]}"
          else
            echo "Environment $ENV_NAME já existe (status $status)"
          fi
          
          # 3) Adicionar colaborador ao repo com permissão de leitura
          curl -L -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/$OWNER/$REPO/collaborators/$COLLAB \
            -d "{\"permission\":\"pull\"}"
