name: Add collaborator & ensure prd environment

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionar colaborador via API
        env:
          GH_TOKEN: ${{ secrets.TESTE_API }}
        run: |
          # dar permissão de leitura (pull) ao colaborador
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/NayaraLetycia/gerenciador_albuns/collaborators/tentaculo-ops \
            -d '{"permission":"pull"}'
      
      - name: Criar ou atualizar ambiente "prd" com revisor exigido
        env:
          GH_TOKEN: ${{ secrets.TESTE_API }}
        run: |
          # Define variáveis
          OWNER="NayaraLetycia"
          REPO="gerenciador_albuns"
          ENV_NAME="prd"
          REVIEWER_LOGIN="tentaculo-ops"

          # Montar JSON para body: revisores obrigatórios
          cat <<EOF > body.json
          {
            "reviewers": [
              {
                "type": "User",
                "reviewer": {
                  "login": "${REVIEWER_LOGIN}"
                }
              }
            ],
            "wait_timer": 0,
            "prevent_self_review": false,
            "deployment_branch_policy": null
          }
EOF

          # Criar ou atualizar o ambiente com proteção de review
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${OWNER}/${REPO}/environments/${ENV_NAME} \
            --data-binary @body.json
