name: Discogs Album Scraper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # permite rodar manualmente

jobs:
  run-discogs-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r "Estado da Arte/discogs_album_app/requirements.txt"

    - name: Rodar Discogs Scraper
      env:
        DISCOGS_TOKEN: ${{ secrets.DISCOGS_TOKEN }}
      run: |
        python "Estado da Arte/discogs_album_app/discogs_album_scraper.py"
